In [1]:
from multi_path_base import *
from joblib import Parallel, delayed
%matplotlib tk 

In [2]:
forecast_with_data=np.load('forecast_with_data.npy')

In [60]:
def optimize(M):    
    X=forecast_with_data[2:M,:,2] #first two sample paths are bad

    disct_temp = disct(N=X.shape[1],dt=1,M=X.shape[0])

    this_model=model_beta_data(disct_temp,X, forecast=forecast_with_data[2:M,:,1] )
    a1,a2=this_model.optimize()
        
    
    return(M, a1, a2)

In [66]:
#M_test=[100,200,300,400,500,600,700,800,900,1265]
M_test=[200,200,200,200,200,200,200,200,200]
cores= min(20,len(M_test))
out=Parallel(n_jobs=cores, verbose=50)(delayed(optimize)(i) for i in M_test);out

[Parallel(n_jobs=9)]: Using backend LokyBackend with 9 concurrent workers.
[Parallel(n_jobs=9)]: Done   1 tasks      | elapsed:   10.9s
[Parallel(n_jobs=9)]: Done   2 out of   9 | elapsed:   11.3s remaining:   39.7s
[Parallel(n_jobs=9)]: Done   3 out of   9 | elapsed:   11.3s remaining:   22.7s
[Parallel(n_jobs=9)]: Done   4 out of   9 | elapsed:   11.6s remaining:   14.5s
[Parallel(n_jobs=9)]: Done   5 out of   9 | elapsed:   11.8s remaining:    9.4s
[Parallel(n_jobs=9)]: Done   6 out of   9 | elapsed:   18.3s remaining:    9.1s
[Parallel(n_jobs=9)]: Done   7 out of   9 | elapsed:  1.1min remaining:   19.1s
[Parallel(n_jobs=9)]: Done   9 out of   9 | elapsed:  2.9min remaining:    0.0s
[Parallel(n_jobs=9)]: Done   9 out of   9 | elapsed:  2.9min finished


[(200,
  array([0.45203881, 0.32303344]),
  b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'),
 (200,
  array([0.02462129, 0.5739058 ]),
  b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'),
 (200,
  array([0.83829224, 0.9253342 ]),
  b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'),
 (200,
  array([0.26215303, 0.96580552]),
  b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'),
 (200,
  array([0.69349139, 0.58293229]),
  b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'),
 (200, array([0.87385934, 0.85206102]), b'ABNORMAL_TERMINATION_IN_LNSRCH'),
 (200,
  array([0.36249145, 0.27192983]),
  b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'),
 (200, array([0.05110277, 0.7916913 ]), b'ABNORMAL_TERMINATION_IN_LNSRCH'),
 (200,
  array([0.97089808, 0.89776706]),
  b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH')]

In [116]:

M_test=np.arange(2,100,2) #,500,10000

#models_M=[]
results=np.empty( (3,len(M_test)), dtype=object)

for j in range(0,len(M_test)):

    X=forecast_with_data[2:M_test[j],:,2] #first two sample paths are bad

    disct_temp = disct(N=X.shape[1],dt=1,M=X.shape[0])

    this_model=model_beta_data(disct_temp,X, forecast=forecast_with_data[2:M_test[j],:,1] )
    optimimuim, message=this_model.optimize()
    print(M_test[j],optimimuim, message)
    results[0,j]=M_test[j]
    results[1,j]=optimimuim
    results[2,j]= message
    del this_model
    

2 [0.69484466 0.1792574 ] b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
4 [0.69433931 1.17992527] b'ABNORMAL_TERMINATION_IN_LNSRCH'
6 [0.677286   1.16313671] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
8 [0.68133194 0.31632161] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
10 [0.69488348 0.19004144] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
12 [1.e-05 1.e-05] b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
14 [0.69102906 0.18653384] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
16 [0.69485342 0.1800443 ] b'ABNORMAL_TERMINATION_IN_LNSRCH'
18 [0.691847  0.1892163] b'ABNORMAL_TERMINATION_IN_LNSRCH'
20 [0.68769057 0.18808265] b'ABNORMAL_TERMINATION_IN_LNSRCH'
22 [0.69414789 0.19049732] b'ABNORMAL_TERMINATION_IN_LNSRCH'
24 [0.69505442 0.18896891] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
26 [0.69540994 0.18987715] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
28 [0.69484466 0.19002378] b'ABNORMAL_TERMINATION_IN_LNSRCH'
30 [0.69484466 0.18904

In [117]:
M_test=np.arange(2,1265,50) #,500,10000

#models_M=[]
results_2=np.empty( (3,len(M_test)), dtype=object)

for j in range(0,len(M_test)):

    X=forecast_with_data[2:M_test[j],:,2] #first two sample paths are bad

    disct_temp = disct(N=X.shape[1],dt=1,M=X.shape[0])

    this_model=model_beta_data(disct_temp,X, forecast=forecast_with_data[2:M_test[j],:,1] )
    optimimuim, message=this_model.optimize()
    print(M_test[j],optimimuim, message)
    results_2[0,j]=M_test[j]
    results_2[1,j]=optimimuim
    results_2[2,j]= message
    del this_model
    

2 [0.69484466 0.1792574 ] b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
52 [0.69484466 0.17992916] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
102 [0.69484466 0.1792574 ] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
152 [0.69484466 0.1792574 ] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
202 [0.6608258  0.32233695] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
252 [0.69703027 0.18656581] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
302 [0.82820225 0.1792574 ] b'ABNORMAL_TERMINATION_IN_LNSRCH'
352 [0.69484466 0.1792574 ] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
402 [0.69484466 0.1792574 ] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
452 [0.69484466 0.1792574 ] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
502 [0.69484466 0.1792574 ] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
552 [0.69484466 0.1792574 ] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
602 [0.69484466 0.1792574 ] b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*

In [119]:
results

array([[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
        68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98],
       [array([0.69484466, 0.1792574 ]), array([0.69433931, 1.17992527]),
        array([0.677286  , 1.16313671]), array([0.68133194, 0.31632161]),
        array([0.69488348, 0.19004144]), array([1.e-05, 1.e-05]),
        array([0.69102906, 0.18653384]), array([0.69485342, 0.1800443 ]),
        array([0.691847 , 0.1892163]), array([0.68769057, 0.18808265]),
        array([0.69414789, 0.19049732]), array([0.69505442, 0.18896891]),
        array([0.69540994, 0.18987715]), array([0.69484466, 0.19002378]),
        array([0.69484466, 0.18904162]), array([0.69050937, 0.1888531 ]),
        array([0.69484466, 0.18950691]), array([0.69484462, 0.18504934]),
        array([0.69484465, 0.18926062]), array([0.69475603, 0.17944419]),
        array([0.69469617, 0.17954585]), array([0.694

In [131]:
sucess_indicies_2=np.where(results_2[2,:]== b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH')
sucess_indicies=np.where(results[2,:]== b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH')

/home/alhaddwt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.
/home/alhaddwt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  


In [133]:
sucess_indicies

(array([ 2,  3,  4,  6, 11, 12, 14, 15, 16, 17, 18, 19, 22, 23, 24, 25, 26,
        30, 34, 37, 38, 39, 41, 42, 43, 44, 45, 47, 48]),)

In [138]:
results[1,sucess_indicies]

array([[array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]), array([0.677286  , 1.16313671]),
        array([0.677286  , 1.16313671]

In [155]:
res2=results_2[1,sucess_indicies_2].reshape((28))

In [196]:
sucess_indicies_2[0][:]=1

In [211]:
sucess_indicies_2

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15]))

In [209]:
sucess_indicies_2[0][:]=1
for i in range(0, )
    np.log(results_2[sucess_indicies_2][0])

array([-0.36406696, -1.71519207])

In [146]:
np.log(results_2[1,sucess_indicies_2][:])

AttributeError: 'numpy.ndarray' object has no attribute 'log'

In [67]:
M=200


X=forecast_with_data[2:M,:,2] #first two sample paths are bad

disct_temp = disct(N=X.shape[1],dt=1,M=X.shape[0])
        
this_model=model_beta_data(disct_temp,X, forecast=forecast_with_data[2:M,:,1] )
this_model.optimize()


(array([0.6866388 , 0.17792916]),
 b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH')

In [13]:
M=100


X=forecast_with_data[2:M,:,2] #first two sample paths are corrupt

disct_temp = disct(N=X.shape[1],dt=1,M=X.shape[0])
        
this_model=model_beta_data(disct_temp,X, forecast=forecast_with_data[2:M,:,1] )
a1,a2=this_model.optimize()


array([0.69484466, 0.22375551])

b'ABNORMAL_TERMINATION_IN_LNSRCH'

(array([0.69484466, 0.22375551]), b'ABNORMAL_TERMINATION_IN_LNSRCH')