In [29]:
from multi_path_base import *
from scipy import interpolate
forecast_with_data=np.load('forecast_with_data.npy')

In [30]:
interp_points=1
forecast_data_inter= np.zeros((2,1217, interp_points*72 ))
x = np.arange(1,72+1,1)
xnew = np.arange(1,72+1,1/interp_points)
counter=0
i=0;j=0
while j< forecast_with_data.shape[0]:
    if  sum(1*np.isnan(forecast_with_data[j,:,1]))==0 and \
        sum(1*np.isnan(forecast_with_data[j,:,2]))==0 and \
        np.max(forecast_with_data[j,:,1])<=1 and \
        np.min(forecast_with_data[j,:,1])>=0 and \
        np.max(forecast_with_data[j,:,2])<=1 and \
        np.min(forecast_with_data[j,:,2])>=0:
        
        #tck_forecast = interpolate.splrep(x, forecast_with_data[j,:,1], s=0)
        #tck_data = interpolate.splrep(x, forecast_with_data[j,:,2], s=0)
        #forecast_data_inter[0,i,:]= interpolate.splev(xnew, tck_forecast, der=0)
        #forecast_data_inter[1,i,:]= interpolate.splev(xnew, tck_data, der=0)
        forecast_data_inter[0,i,:]= forecast_with_data[j,:,1]
        forecast_data_inter[1,i,:]= forecast_with_data[j,:,2]
        i+=1
    j+=1

In [31]:
forecast_data_inter.shape

(2, 1217, 72)

In [51]:
N=73
#M=forecast_data_inter.shape[1]
M=100
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]
V = np.insert(V, 0, 0,axis=1) #insert a zero as the first point to account for forecast delay erro
this_model=model_beta_flex(disct_temp,V, forecast= p)


In [52]:
this_model.optimize()

(array([0.5937651 , 0.79329554]),
 b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH')

In [53]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=500
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)

In [54]:
this_model.optimize()

(array([8.72160813, 2.33880891]),
 b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH')

In [55]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=800
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)

In [56]:
this_model.optimize()

(array([12.32867695,  2.1602106 ]),
 b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH')

In [57]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=1000
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)

In [58]:
this_model.optimize()

(array([12.06135847,  2.21912519]), b'ABNORMAL_TERMINATION_IN_LNSRCH')

In [59]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=1216
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)

In [60]:
this_model.optimize()

(array([11.69054785,  2.23761191]), b'ABNORMAL_TERMINATION_IN_LNSRCH')

In [61]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=1216
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)

In [62]:
this_model.optimize(param_initial=np.array(( 12,2 )) )

(array([11.69132722,  2.23743167]), b'ABNORMAL_TERMINATION_IN_LNSRCH')