In [1]:
from multi_path_base import *
from scipy import interpolate
forecast_with_data=np.load('forecast_with_data.npy')

In [2]:
interp_points=1
forecast_data_inter= np.zeros((2,1217, interp_points*72 ))
x = np.arange(1,72+1,1)
xnew = np.arange(1,72+1,1/interp_points)
counter=0
i=0;j=0
while j< forecast_with_data.shape[0]:
    if  sum(1*np.isnan(forecast_with_data[j,:,1]))==0 and \
        sum(1*np.isnan(forecast_with_data[j,:,2]))==0 and \
        np.max(forecast_with_data[j,:,1])<=1 and \
        np.min(forecast_with_data[j,:,1])>=0 and \
        np.max(forecast_with_data[j,:,2])<=1 and \
        np.min(forecast_with_data[j,:,2])>=0:
        
        #tck_forecast = interpolate.splrep(x, forecast_with_data[j,:,1], s=0)
        #tck_data = interpolate.splrep(x, forecast_with_data[j,:,2], s=0)
        #forecast_data_inter[0,i,:]= interpolate.splev(xnew, tck_forecast, der=0)
        #forecast_data_inter[1,i,:]= interpolate.splev(xnew, tck_data, der=0)
        forecast_data_inter[0,i,:]= forecast_with_data[j,:,1]
        forecast_data_inter[1,i,:]= forecast_with_data[j,:,2]
        i+=1
    j+=1

In [15]:
i

1217

In [9]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=100
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)


In [10]:
this_model.optimize()

(array([6.59606798, 1.90405951]),
 b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH')

In [11]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=500
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)

In [12]:
this_model.optimize()

(array([8.72160813, 2.33880891]),
 b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH')

In [13]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=800
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)

In [14]:
this_model.optimize()

(array([12.32867695,  2.1602106 ]),
 b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH')

In [16]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=1000
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)

In [17]:
this_model.optimize()

(array([12.06135847,  2.21912519]), b'ABNORMAL_TERMINATION_IN_LNSRCH')

In [18]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=1216
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)

In [19]:
this_model.optimize()

(array([11.69054785,  2.23761191]), b'ABNORMAL_TERMINATION_IN_LNSRCH')

In [22]:
N=forecast_data_inter.shape[2]
#M=forecast_data_inter.shape[1]
M=1216
dt=1

#forecast_data_inter[0,:,:] #forecast

disct_temp = disct(N,dt,M)
p=forecast_data_inter[0,:M,:]
V= forecast_data_inter[1,:M,:] -forecast_data_inter[0,:M,:]

this_model=model_beta_flex(disct_temp,V, forecast= p)

In [24]:
this_model.optimize(param_initial=np.array(( 12,1.5 )) )

(array([11.68794424,  2.238174  ]), b'ABNORMAL_TERMINATION_IN_LNSRCH')